I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/cap/capitulo 2.rpy", line 302, in script
    $ vr == True
  File "game/cap/capitulo 2.rpy", line 302, in script
    $ vr == True
  File "game/cap/capitulo 2.rpy", line 302, in <module>
    $ vr == True
NameError: name 'vr' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\zeelt\OneDrive\Escritorio\Renpy\renpy-8.0.3-sdk\renpy\bootstrap.py", line 277, in bootstrap
    renpy.main.main()
  File "C:\Users\zeelt\OneDrive\Escritorio\Renpy\renpy-8.0.3-sdk\renpy\main.py", line 558, in main
    renpy.game.context().run(node)
  File "game/cap/capitulo 2.rpy", line 302, in script
    $ vr == True
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python3.9/site-packages/future/utils/__init__.py", line 441, in raise_
  File "game/cap/capitulo 2.rpy", line 302, in script
    $ vr == True
  File "C:\Users\zeelt\OneDrive\Escritorio\Renpy\renpy-8.0.3-sdk\renpy\ast.py", line 1131, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\zeelt\OneDrive\Escritorio\Renpy\renpy-8.0.3-sdk\renpy\python.py", line 1061, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/cap/capitulo 2.rpy", line 302, in <module>
    $ vr == True
NameError: name 'vr' is not defined

Windows-10-10.0.22621 AMD64
Ren'Py 8.0.3.22090809
Inability Hero Pre-Alpha
Wed Mar 29 08:49:46 2023
